package main

import (
	"github.com/aws-opsworks/mcp-server/config"
	"github.com/aws-opsworks/mcp-server/models"
	tools_x_amz_target_opsworks_20130218_disassociateelasticip "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_disassociateelasticip"
	tools_x_amz_target_opsworks_20130218_describeraidarrays "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeraidarrays"
	tools_x_amz_target_opsworks_20130218_registerecscluster "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_registerecscluster"
	tools_x_amz_target_opsworks_20130218_deregisterelasticip "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deregisterelasticip"
	tools_x_amz_target_opsworks_20130218_listtags "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_listtags"
	tools_x_amz_target_opsworks_20130218_grantaccess "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_grantaccess"
	tools_x_amz_target_opsworks_20130218_updateinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updateinstance"
	tools_x_amz_target_opsworks_20130218_describemyuserprofile "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describemyuserprofile"
	tools_x_amz_target_opsworks_20130218_registerelasticip "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_registerelasticip"
	tools_x_amz_target_opsworks_20130218_updateuserprofile "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updateuserprofile"
	tools_x_amz_target_opsworks_20130218_describedeployments "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describedeployments"
	tools_x_amz_target_opsworks_20130218_stopinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_stopinstance"
	tools_x_amz_target_opsworks_20130218_untagresource "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_untagresource"
	tools_x_amz_target_opsworks_20130218_rebootinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_rebootinstance"
	tools_x_amz_target_opsworks_20130218_unassigninstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_unassigninstance"
	tools_x_amz_target_opsworks_20130218_describeuserprofiles "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeuserprofiles"
	tools_x_amz_target_opsworks_20130218_describeserviceerrors "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeserviceerrors"
	tools_x_amz_target_opsworks_20130218_deregisterinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deregisterinstance"
	tools_x_amz_target_opsworks_20130218_deregistervolume "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deregistervolume"
	tools_x_amz_target_opsworks_20130218_describestacksummary "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describestacksummary"
	tools_x_amz_target_opsworks_20130218_clonestack "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_clonestack"
	tools_x_amz_target_opsworks_20130218_detachelasticloadbalancer "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_detachelasticloadbalancer"
	tools_x_amz_target_opsworks_20130218_startstack "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_startstack"
	tools_x_amz_target_opsworks_20130218_createapp "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_createapp"
	tools_x_amz_target_opsworks_20130218_deregisterecscluster "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deregisterecscluster"
	tools_x_amz_target_opsworks_20130218_startinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_startinstance"
	tools_x_amz_target_opsworks_20130218_createuserprofile "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_createuserprofile"
	tools_x_amz_target_opsworks_20130218_deleteapp "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deleteapp"
	tools_x_amz_target_opsworks_20130218_describeoperatingsystems "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeoperatingsystems"
	tools_x_amz_target_opsworks_20130218_deleteinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deleteinstance"
	tools_x_amz_target_opsworks_20130218_updatelayer "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updatelayer"
	tools_x_amz_target_opsworks_20130218_createdeployment "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_createdeployment"
	tools_x_amz_target_opsworks_20130218_stopstack "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_stopstack"
	tools_x_amz_target_opsworks_20130218_describecommands "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describecommands"
	tools_x_amz_target_opsworks_20130218_deleteuserprofile "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deleteuserprofile"
	tools_x_amz_target_opsworks_20130218_attachelasticloadbalancer "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_attachelasticloadbalancer"
	tools_x_amz_target_opsworks_20130218_registervolume "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_registervolume"
	tools_x_amz_target_opsworks_20130218_updatestack "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updatestack"
	tools_x_amz_target_opsworks_20130218_describepermissions "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describepermissions"
	tools_x_amz_target_opsworks_20130218_updatemyuserprofile "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updatemyuserprofile"
	tools_x_amz_target_opsworks_20130218_deregisterrdsdbinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deregisterrdsdbinstance"
	tools_x_amz_target_opsworks_20130218_createstack "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_createstack"
	tools_x_amz_target_opsworks_20130218_updatevolume "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updatevolume"
	tools_x_amz_target_opsworks_20130218_describeelasticloadbalancers "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeelasticloadbalancers"
	tools_x_amz_target_opsworks_20130218_deletelayer "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deletelayer"
	tools_x_amz_target_opsworks_20130218_settimebasedautoscaling "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_settimebasedautoscaling"
	tools_x_amz_target_opsworks_20130218_updaterdsdbinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updaterdsdbinstance"
	tools_x_amz_target_opsworks_20130218_describestackprovisioningparameters "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describestackprovisioningparameters"
	tools_x_amz_target_opsworks_20130218_describeelasticips "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeelasticips"
	tools_x_amz_target_opsworks_20130218_describetimebasedautoscaling "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describetimebasedautoscaling"
	tools_x_amz_target_opsworks_20130218_describeagentversions "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeagentversions"
	tools_x_amz_target_opsworks_20130218_deletestack "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_deletestack"
	tools_x_amz_target_opsworks_20130218_describevolumes "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describevolumes"
	tools_x_amz_target_opsworks_20130218_describestacks "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describestacks"
	tools_x_amz_target_opsworks_20130218_registerrdsdbinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_registerrdsdbinstance"
	tools_x_amz_target_opsworks_20130218_updateapp "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updateapp"
	tools_x_amz_target_opsworks_20130218_gethostnamesuggestion "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_gethostnamesuggestion"
	tools_x_amz_target_opsworks_20130218_tagresource "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_tagresource"
	tools_x_amz_target_opsworks_20130218_assigninstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_assigninstance"
	tools_x_amz_target_opsworks_20130218_describerdsdbinstances "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describerdsdbinstances"
	tools_x_amz_target_opsworks_20130218_setloadbasedautoscaling "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_setloadbasedautoscaling"
	tools_x_amz_target_opsworks_20130218_createinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_createinstance"
	tools_x_amz_target_opsworks_20130218_registerinstance "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_registerinstance"
	tools_x_amz_target_opsworks_20130218_assignvolume "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_assignvolume"
	tools_x_amz_target_opsworks_20130218_describeapps "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeapps"
	tools_x_amz_target_opsworks_20130218_setpermission "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_setpermission"
	tools_x_amz_target_opsworks_20130218_describelayers "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describelayers"
	tools_x_amz_target_opsworks_20130218_createlayer "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_createlayer"
	tools_x_amz_target_opsworks_20130218_updateelasticip "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_updateelasticip"
	tools_x_amz_target_opsworks_20130218_describeloadbasedautoscaling "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeloadbasedautoscaling"
	tools_x_amz_target_opsworks_20130218_associateelasticip "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_associateelasticip"
	tools_x_amz_target_opsworks_20130218_unassignvolume "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_unassignvolume"
	tools_x_amz_target_opsworks_20130218_describeecsclusters "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeecsclusters"
	tools_x_amz_target_opsworks_20130218_describeinstances "github.com/aws-opsworks/mcp-server/tools/x_amz_target_opsworks_20130218_describeinstances"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_opsworks_20130218_disassociateelasticip.CreateDisassociateelasticipTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeraidarrays.CreateDescriberaidarraysTool(cfg),
		tools_x_amz_target_opsworks_20130218_registerecscluster.CreateRegisterecsclusterTool(cfg),
		tools_x_amz_target_opsworks_20130218_deregisterelasticip.CreateDeregisterelasticipTool(cfg),
		tools_x_amz_target_opsworks_20130218_listtags.CreateListtagsTool(cfg),
		tools_x_amz_target_opsworks_20130218_grantaccess.CreateGrantaccessTool(cfg),
		tools_x_amz_target_opsworks_20130218_updateinstance.CreateUpdateinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_describemyuserprofile.CreateDescribemyuserprofileTool(cfg),
		tools_x_amz_target_opsworks_20130218_registerelasticip.CreateRegisterelasticipTool(cfg),
		tools_x_amz_target_opsworks_20130218_updateuserprofile.CreateUpdateuserprofileTool(cfg),
		tools_x_amz_target_opsworks_20130218_describedeployments.CreateDescribedeploymentsTool(cfg),
		tools_x_amz_target_opsworks_20130218_stopinstance.CreateStopinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_opsworks_20130218_rebootinstance.CreateRebootinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_unassigninstance.CreateUnassigninstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeuserprofiles.CreateDescribeuserprofilesTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeserviceerrors.CreateDescribeserviceerrorsTool(cfg),
		tools_x_amz_target_opsworks_20130218_deregisterinstance.CreateDeregisterinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_deregistervolume.CreateDeregistervolumeTool(cfg),
		tools_x_amz_target_opsworks_20130218_describestacksummary.CreateDescribestacksummaryTool(cfg),
		tools_x_amz_target_opsworks_20130218_clonestack.CreateClonestackTool(cfg),
		tools_x_amz_target_opsworks_20130218_detachelasticloadbalancer.CreateDetachelasticloadbalancerTool(cfg),
		tools_x_amz_target_opsworks_20130218_startstack.CreateStartstackTool(cfg),
		tools_x_amz_target_opsworks_20130218_createapp.CreateCreateappTool(cfg),
		tools_x_amz_target_opsworks_20130218_deregisterecscluster.CreateDeregisterecsclusterTool(cfg),
		tools_x_amz_target_opsworks_20130218_startinstance.CreateStartinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_createuserprofile.CreateCreateuserprofileTool(cfg),
		tools_x_amz_target_opsworks_20130218_deleteapp.CreateDeleteappTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeoperatingsystems.CreateDescribeoperatingsystemsTool(cfg),
		tools_x_amz_target_opsworks_20130218_deleteinstance.CreateDeleteinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_updatelayer.CreateUpdatelayerTool(cfg),
		tools_x_amz_target_opsworks_20130218_createdeployment.CreateCreatedeploymentTool(cfg),
		tools_x_amz_target_opsworks_20130218_stopstack.CreateStopstackTool(cfg),
		tools_x_amz_target_opsworks_20130218_describecommands.CreateDescribecommandsTool(cfg),
		tools_x_amz_target_opsworks_20130218_deleteuserprofile.CreateDeleteuserprofileTool(cfg),
		tools_x_amz_target_opsworks_20130218_attachelasticloadbalancer.CreateAttachelasticloadbalancerTool(cfg),
		tools_x_amz_target_opsworks_20130218_registervolume.CreateRegistervolumeTool(cfg),
		tools_x_amz_target_opsworks_20130218_updatestack.CreateUpdatestackTool(cfg),
		tools_x_amz_target_opsworks_20130218_describepermissions.CreateDescribepermissionsTool(cfg),
		tools_x_amz_target_opsworks_20130218_updatemyuserprofile.CreateUpdatemyuserprofileTool(cfg),
		tools_x_amz_target_opsworks_20130218_deregisterrdsdbinstance.CreateDeregisterrdsdbinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_createstack.CreateCreatestackTool(cfg),
		tools_x_amz_target_opsworks_20130218_updatevolume.CreateUpdatevolumeTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeelasticloadbalancers.CreateDescribeelasticloadbalancersTool(cfg),
		tools_x_amz_target_opsworks_20130218_deletelayer.CreateDeletelayerTool(cfg),
		tools_x_amz_target_opsworks_20130218_settimebasedautoscaling.CreateSettimebasedautoscalingTool(cfg),
		tools_x_amz_target_opsworks_20130218_updaterdsdbinstance.CreateUpdaterdsdbinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_describestackprovisioningparameters.CreateDescribestackprovisioningparametersTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeelasticips.CreateDescribeelasticipsTool(cfg),
		tools_x_amz_target_opsworks_20130218_describetimebasedautoscaling.CreateDescribetimebasedautoscalingTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeagentversions.CreateDescribeagentversionsTool(cfg),
		tools_x_amz_target_opsworks_20130218_deletestack.CreateDeletestackTool(cfg),
		tools_x_amz_target_opsworks_20130218_describevolumes.CreateDescribevolumesTool(cfg),
		tools_x_amz_target_opsworks_20130218_describestacks.CreateDescribestacksTool(cfg),
		tools_x_amz_target_opsworks_20130218_registerrdsdbinstance.CreateRegisterrdsdbinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_updateapp.CreateUpdateappTool(cfg),
		tools_x_amz_target_opsworks_20130218_gethostnamesuggestion.CreateGethostnamesuggestionTool(cfg),
		tools_x_amz_target_opsworks_20130218_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_opsworks_20130218_assigninstance.CreateAssigninstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_describerdsdbinstances.CreateDescriberdsdbinstancesTool(cfg),
		tools_x_amz_target_opsworks_20130218_setloadbasedautoscaling.CreateSetloadbasedautoscalingTool(cfg),
		tools_x_amz_target_opsworks_20130218_createinstance.CreateCreateinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_registerinstance.CreateRegisterinstanceTool(cfg),
		tools_x_amz_target_opsworks_20130218_assignvolume.CreateAssignvolumeTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeapps.CreateDescribeappsTool(cfg),
		tools_x_amz_target_opsworks_20130218_setpermission.CreateSetpermissionTool(cfg),
		tools_x_amz_target_opsworks_20130218_describelayers.CreateDescribelayersTool(cfg),
		tools_x_amz_target_opsworks_20130218_createlayer.CreateCreatelayerTool(cfg),
		tools_x_amz_target_opsworks_20130218_updateelasticip.CreateUpdateelasticipTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeloadbasedautoscaling.CreateDescribeloadbasedautoscalingTool(cfg),
		tools_x_amz_target_opsworks_20130218_associateelasticip.CreateAssociateelasticipTool(cfg),
		tools_x_amz_target_opsworks_20130218_unassignvolume.CreateUnassignvolumeTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeecsclusters.CreateDescribeecsclustersTool(cfg),
		tools_x_amz_target_opsworks_20130218_describeinstances.CreateDescribeinstancesTool(cfg),
	}
}
